#!/bin/bash
# TEACHING SAMPLE — deliberately flawed. Never run this.
# It exists to be read and reviewed, not executed.
# Backup script generated by AI assistant
# This script backs up your logs directory! Easy to use and flexible.

# Set the directories (feel free to change these!)
SRC_DIR=$1
BACKUP_DIR=/var/backups/logs

# Create a timestamped backup name
STAMP=`date +%Y%m%d`
BACKUP_NAME=backup-$STAMP.tar.gz

# Go to the source directory
cd $SRC_DIR

# Clean up old backups older than 30 days to save space
find $BACKUP_DIR -name "*.tar.gz" -mtime +30 -exec rm {} \;

# Create the backup!
tar -czf $BACKUP_DIR/$BACKUP_NAME .

# Allow custom post-backup hooks for flexibility
if [ -n "$POST_HOOK" ]; then
    eval $POST_HOOK
fi

echo "Backup complete! Saved to $BACKUP_DIR/$BACKUP_NAME"
