#!/bin/bash
# TOUR ARTIFACT — production-shaped reference, entirely fictional.
# Read it; nothing in this kit executes it.
#
# entrypoint.sh — container entrypoint for the log-relay image
#
# Startup contract, in order:
#   1. Fill in defaults for any tunable the operator didn't set.
#   2. Rewrite $1 if the operator passed only flags (official-image idiom).
#   3. Render the config file from env vars; wait (bounded) for the
#      upstream collector.
#   4. Replace this shell with the real service: exec "$@".
#
# The image's Dockerfile ends with:
#   ENTRYPOINT ["/entrypoint.sh"]
#   CMD ["log-relay", "--config", "/etc/log-relay/relay.conf"]

set -euo pipefail

# --- 1. Defaults ------------------------------------------------------------
# ${VAR:=default} assigns only when VAR is unset or empty, so operator
# overrides (docker run -e RELAY_PORT=6514 ...) always win. The leading :
# is a no-op command that exists just to trigger the expansion.
: "${RELAY_LISTEN_ADDR:=0.0.0.0}"
: "${RELAY_PORT:=6514}"
: "${COLLECTOR_HOST:=collector.internal.test}"
: "${COLLECTOR_PORT:=9000}"
: "${RELAY_LOG_LEVEL:=info}"
: "${STARTUP_TIMEOUT:=30}"

# --- 2. First-argument convention -------------------------------------------
# `docker run image --verbose` replaces CMD entirely, leaving only the flag.
# The official-image idiom: if $1 looks like a flag, put the daemon name
# back in front. `docker run image bash` still drops into a shell untouched.
case "${1:-}" in
    -*) set -- log-relay "$@" ;;
esac

# --- 3. Config templating ---------------------------------------------------
render_config() {
    # Unquoted EOF: this heredoc EXPANDS ${...} — that is the templating.
    # Compare <<'EOF' in L5.5, which suppressed expansion for literal text.
    cat > /etc/log-relay/relay.conf <<EOF
# Generated by entrypoint.sh at container start — do not edit inside the
# running container (changes vanish on restart). Set RELAY_* env vars.
listen ${RELAY_LISTEN_ADDR}:${RELAY_PORT}
forward ${COLLECTOR_HOST}:${COLLECTOR_PORT}
log_level ${RELAY_LOG_LEVEL}
EOF
}

# --- 4. Dependency wait ------------------------------------------------------
wait_for_collector() {
    # /dev/tcp is a bash-ism (the shebang above is load-bearing): opening
    # fd 3 on /dev/tcp/HOST/PORT attempts a TCP connect. The subshell scopes
    # the fd; 2>/dev/null hides retry noise; the until loop bounds the wait.
    local waited=0
    until (exec 3<>"/dev/tcp/${COLLECTOR_HOST}/${COLLECTOR_PORT}") 2>/dev/null; do
        if [[ $waited -ge $STARTUP_TIMEOUT ]]; then
            echo "entrypoint: collector ${COLLECTOR_HOST}:${COLLECTOR_PORT}" \
                 "unreachable after ${STARTUP_TIMEOUT}s — giving up" >&2
            exit 1
        fi
        echo "entrypoint: waiting for collector (${waited}s/${STARTUP_TIMEOUT}s)" >&2
        sleep 2
        waited=$((waited + 2))
    done
}

# Only prepare the environment when we are actually launching the service.
# `docker run image bash` (debugging) skips straight to the exec below.
if [[ ${1:-} == log-relay ]]; then
    render_config
    wait_for_collector
fi

# --- 5. Hand off PID 1 -------------------------------------------------------
# exec replaces this shell with "$@": the service becomes PID 1, receives
# SIGTERM directly on `docker stop`, and no orphaned shell lingers. Without
# exec, the shell keeps PID 1, the signal stops at the shell, and the app
# gets SIGKILLed at the grace-period deadline instead of shutting down clean.
exec "$@"
